quarkus:
  http:
    port: 8080
    cors:
      origins: "${CORS_ORIGINS:https://yapeapp.com,https://www.yapeapp.com}"
      headers: "accept,authorization,content-type,x-requested-with"
      methods: "GET,POST,PUT,DELETE,OPTIONS"
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    reactive:
      url: ${DB_URL}
      max-size: 20
      idle-timeout: 10M
      postgresql:
        ssl-mode: require


  hibernate-orm:
    database:
      generation: validate
    log:
      sql: false

  smallrye-openapi:
    servers: "https://api.yapeapp.com"

  mailer:
    from: noreply@yapeapp.com
    host: ${SMTP_HOST}
    port: ${SMTP_PORT:587}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    start-tls: required


jwt:
  issuer: "https://api.yapeapp.com"
  access-token:
    duration: PT15M
  refresh-token:
    duration: P30D

mp:
  jwt:
    verify:
      issuer: "https://api.yapeapp.com"

smallrye:
  jwt:
    sign:
      key-secret: "${JWT_SECRET}"
      algorithm: HS256

yapechamo:
  app:
    environment: "production"